const allData = [
  {
    id: 1,
    businessName: '모구리야영장',
    phoneNumber: '064-760-3408',
    address: '제주특별자치도 서귀포시 성산읍 서성일로 260',
    latitude: 33.40624241,
    longitude: 126.8220003,
    glampingCount: null,
    caravanCount: null,
    campingDeckCount: null,
    outdoorCampingCount: null,
    hasToilet: null,
    hasShower: null,
    hasWashbasin: 'Y',
    parkingCapacity: null,
    tags: '조용한, 아늑한, 취사가능, 숲, 청결에 민감한',
    img: 'https://peton.me/data/file/addPlace/%EB%A6%AC%EC%8D%B8%EC%B9%B4%EB%9D%BC%EB%B0%98_%EC%9D%BC%EA%B3%BC%EB%8C%80%EC%88%98%EB%A1%9C27%EB%B2%88%EA%B8%B8_1.jpg',
  },
  {
    id: 2,
    businessName: '드르쿰다 in 성산 카라반',
    phoneNumber: '064-901-2197',
    address: '제주특별자치도 서귀포시 성산읍 섭지코지로25번길 64',
    latitude: 33.4445023,
    longitude: 126.9190809,
    glampingCount: null,
    caravanCount: null,
    campingDeckCount: null,
    outdoorCampingCount: null,
    hasToilet: null,
    hasShower: null,
    hasWashbasin: null,
    parkingCapacity: null,
    tags: '로맨틱한, 평화로운, 반려동물 친화적인, 개방적인, 신나는',
    img: 'https://images.app.goo.gl/BceHwMnMtHxAi8rV7',
  },
  {
    id: 3,
    businessName: '성산하수처리장잔디밭야영지',
    phoneNumber: '064-750-7985',
    address: '제주특별자치도 서귀포시 성산읍 고성동서로 115',
    latitude: 33.4518928,
    longitude: 126.918383,
    glampingCount: null,
    caravanCount: null,
    campingDeckCount: null,
    outdoorCampingCount: null,
    hasToilet: null,
    hasShower: null,
    hasWashbasin: null,
    parkingCapacity: null,
    tags: '친근한, 개방적인, 도전적인',
    img: 'https://images.app.goo.gl/yC8YqDaNjXoXCmyJ8',
  },
  {
    id: 4,
    businessName: '스타빌',
    phoneNumber: '064-793-9100',
    address: '제주특별자치도 서귀포시 안덕면 광평로 34-154',
    latitude: 33.33841521,
    longitude: 126.3954246,
    glampingCount: null,
    caravanCount: null,
    campingDeckCount: null,
    outdoorCampingCount: null,
    hasToilet: 'Y',
    hasShower: 'Y',
    hasWashbasin: 'Y',
    parkingCapacity: null,
    tags: '글램핑, 조용한, 아늑한, 로맨틱한, 평화로운, 들판, 안전한, 청결에 민감한',
    img: 'https://images.app.goo.gl/ZLjptZkwbU8LMULM6',
  },
  {
    id: 5,
    businessName: '동광농촌체험마을',
    phoneNumber: '064-794-2298',
    address: '제주특별자치도 서귀포시 안덕면 동광로 107',
    latitude: 33.30670532,
    longitude: 126.3370378,
    glampingCount: null,
    caravanCount: null,
    campingDeckCount: null,
    outdoorCampingCount: null,
    hasToilet: null,
    hasShower: null,
    hasWashbasin: 'Y',
    parkingCapacity: null,
    tags: '신나는, 친근한, 개방적인, 도전적인, 시원한, 취사가능, 들판, 바베큐',
    img: 'https://images.app.goo.gl/swGK3numTYoeCbUc9',
  },
  {
    id: 6,
    businessName: '제주캠핑카라반',
    phoneNumber: '064-787-8202',
    address: '제주특별자치도 서귀포시 표선면 표선동서로 324-18',
    latitude: 33.32994006,
    longitude: 126.8382291,
    glampingCount: null,
    caravanCount: null,
    campingDeckCount: null,
    outdoorCampingCount: null,
    hasToilet: null,
    hasShower: null,
    hasWashbasin: 'Y',
    parkingCapacity: null,
    tags: '아늑한, 친근한, 개방적인, 도전적인, 바다, 별, 시원한, 취사가능, 바베큐, 반려동물 친화적인, 카라반',
    img: 'https://images.app.goo.gl/ghf3rds1iKin7BMR9',
  },
  {
    id: 7,
    businessName: '메이더카라반',
    phoneNumber: '064-783-2200',
    address: '제주특별자치도 제주시 구좌읍 일주동로 1622',
    latitude: 33.55238306,
    longitude: 126.7058337,
    glampingCount: null,
    caravanCount: null,
    campingDeckCount: null,
    outdoorCampingCount: null,
    hasToilet: null,
    hasShower: null,
    hasWashbasin: null,
    parkingCapacity: null,
    tags: '카라반, 바다, 별, 조용한, 아늑한, 로맨틱한, 평화로운, 취사가능, 바베큐',
    img: 'https://images.app.goo.gl/PP6eCj452wz2Kqgy6',
  },
  {
    id: 8,
    businessName: '디포레카라반파크',
    phoneNumber: '064-784-2417',
    address: '제주특별자치도 제주시 구좌읍 송당6길 78-1',
    latitude: 33.46483147,
    longitude: 126.7811913,
    glampingCount: null,
    caravanCount: null,
    campingDeckCount: null,
    outdoorCampingCount: null,
    hasToilet: 'Y',
    hasShower: null,
    hasWashbasin: null,
    parkingCapacity: null,
    tags: '조용한, 아늑한, 친근한, 숲, 카라반, 조용한, 아늑한, 친근한, 신비로운, 평화로운, 시원한, 바베큐',
    img: 'https://images.app.goo.gl/gcNj5phGkT81PoUg6',
  },
  {
    id: 9,
    businessName: '종달야영장',
    phoneNumber: null,
    address: '제주특별자치도 제주시 구좌읍 세종로 353',
    latitude: 33.49878663,
    longitude: 126.8907008,
    glampingCount: null,
    caravanCount: null,
    campingDeckCount: null,
    outdoorCampingCount: null,
    hasToilet: null,
    hasShower: null,
    hasWashbasin: null,
    parkingCapacity: null,
    tags: '아늑한, 친근한, 안전한, 평화로운, 청결에 민감한, 들판',
    img: 'https://images.app.goo.gl/6eDrSpF4aR22CP2E8',
  },
  {
    id: 10,
    businessName: '곽지해수욕장야영장',
    phoneNumber: null,
    address: '제주특별자치도 제주시 애월읍 곽지5길 28',
    latitude: 33.44980004,
    longitude: 126.3049037,
    glampingCount: null,
    caravanCount: null,
    campingDeckCount: null,
    outdoorCampingCount: null,
    hasToilet: null,
    hasShower: null,
    hasWashbasin: null,
    parkingCapacity: null,
    tags: '바다, 개방적인, 도전적인, 시원한, 반려동물 친화적인, 별',
    img: 'https://images.app.goo.gl/XgaAjEgaYq8Dvvis5',
  },
  {
    id: 11,
    businessName: '에코힐글램핑',
    phoneNumber: '064-743-0060',
    address: '제주특별자치도 제주시 애월읍 광령평화8길 22',
    latitude: 33.44986093,
    longitude: 126.4408328,
    glampingCount: null,
    caravanCount: null,
    campingDeckCount: null,
    outdoorCampingCount: null,
    hasToilet: null,
    hasShower: null,
    hasWashbasin: null,
    parkingCapacity: null,
    tags: '신나는, 친근한, 개방적인, 도전적인, 시원한, 글램핑, 물놀이 시설',
    img: 'https://images.app.goo.gl/gYWUHgQhxmB8jvwg7',
  },
  {
    id: 12,
    businessName: '에코그린캠핑장',
    phoneNumber: '0507-1322-8649',
    address: '제주특별자치도 제주시 애월읍 중산간서로 5587',
    latitude: 33.44429936,
    longitude: 126.3338771,
    glampingCount: '9',
    caravanCount: '9',
    campingDeckCount: '13',
    outdoorCampingCount: 'Y',
    hasToilet: 'Y',
    hasShower: 'Y',
    hasWashbasin: null,
    parkingCapacity: null,
    tags: '신나는, 개방적인, 도전적인, 물놀이 시설, 들판, 별',
    img: 'https://images.app.goo.gl/LPRNPnDD9xb7YwJe6',
  },
  {
    id: 13,
    businessName: '케이글램핑 애월',
    phoneNumber: null,
    address: '제주특별자치도 제주시 애월읍 소길남길 120',
    latitude: 33.42422779,
    longitude: 126.37638,
    glampingCount: '20',
    caravanCount: null,
    campingDeckCount: null,
    outdoorCampingCount: 'Y',
    hasToilet: 'Y',
    hasShower: null,
    hasWashbasin: null,
    parkingCapacity: null,
    tags: '글램핑, 들판, 아늑한, 안전한, 물놀이 시설, 바베큐, 청결에 민감한, 취사가능',
    img: 'https://images.app.goo.gl/iwPVW7SBnrhV4NTY6',
  },
  {
    id: 14,
    businessName: '홍스랜드 글램핑',
    phoneNumber: null,
    address: '제주특별자치도 제주시 애월읍 어음13길 25-45',
    latitude: 33.40287749,
    longitude: 126.3472689,
    glampingCount: null,
    caravanCount: null,
    campingDeckCount: null,
    outdoorCampingCount: null,
    hasToilet: null,
    hasShower: null,
    hasWashbasin: null,
    parkingCapacity: null,
    tags: '신나는, 글램핑, 들판, 친근한, 개방적인, 취사가능, 바베큐, 물놀이 시설',
    img: 'https://images.app.goo.gl/ktRGhTvTLo3knSse8',
  },
  {
    id: 15,
    businessName: '폴리파크카라반',
    phoneNumber: '064-799-0166',
    address: '제주특별자치도 제주시 애월읍 산록서로 18',
    latitude: 33.38670817,
    longitude: 126.3759978,
    glampingCount: null,
    caravanCount: null,
    campingDeckCount: null,
    outdoorCampingCount: null,
    hasToilet: 'Y',
    hasShower: 'Y',
    hasWashbasin: null,
    parkingCapacity: null,
    tags: '들판, 카라반, 조용한, 아늑한, 로맨틱한, 안전한, 취사가능, 바베큐, 별',
    img: 'https://images.app.goo.gl/1Dws1UC6oycRjrNj9',
  },
  {
    id: 16,
    businessName: '별헤는밤',
    phoneNumber: '0507-1408-7802',
    address: '제주특별자치도 제주시 애월읍 광상로 348',
    latitude: 33.44333811,
    longitude: 126.396639,
    glampingCount: null,
    caravanCount: null,
    campingDeckCount: null,
    outdoorCampingCount: null,
    hasToilet: null,
    hasShower: null,
    hasWashbasin: null,
    parkingCapacity: null,
    tags: '조용한, 아늑한, 글램핑, 들판, 별, 바다, 바베큐, 취사가능',
    img: 'https://images.app.goo.gl/F7Y37MzjJnUYqdPa8',
  },
  {
    id: 17,
    businessName: '캠핑스토리',
    phoneNumber: null,
    address: '제주특별자치도 제주시 애월읍 하소로 746',
    latitude: 33.41755307,
    longitude: 126.3949064,
    glampingCount: null,
    caravanCount: null,
    campingDeckCount: null,
    outdoorCampingCount: null,
    hasToilet: null,
    hasShower: null,
    hasWashbasin: 'Y',
    parkingCapacity: null,
    tags: '숲, 별, 아늑한, 조용한, 신비로운, 평화로운, 청결에 민감한, 취사가능, 바베큐',
    img: 'https://images.app.goo.gl/XostBNHZfMWaJtbQ8',
  },
  {
    id: 18,
    businessName: '유수암캠핑장',
    phoneNumber: '0507-1352-6696',
    address: '제주특별자치도 제주시 애월읍 하소로 684-25',
    latitude: 33.42213177,
    longitude: 126.3936946,
    glampingCount: null,
    caravanCount: null,
    campingDeckCount: null,
    outdoorCampingCount: null,
    hasToilet: null,
    hasShower: null,
    hasWashbasin: null,
    parkingCapacity: null,
    tags: '들판, 별, 조용한, 친근한, 평화로운, 바베큐',
    img: 'https://images.app.goo.gl/nbvh2NWuzbZb48RJ8',
  },
  {
    id: 19,
    businessName: '녹고뫼캠핑장',
    phoneNumber: '064-799-8118',
    address: '제주특별자치도 제주시 애월읍 유수암평화10길 175-78',
    latitude: 33.41314679,
    longitude: 126.4185293,
    glampingCount: null,
    caravanCount: null,
    campingDeckCount: null,
    outdoorCampingCount: null,
    hasToilet: null,
    hasShower: null,
    hasWashbasin: null,
    parkingCapacity: null,
    tags: '숲, 별, 들판, 조용한, 로맨틱한, 평화로운, 반려동물 친화적인, 청결에 민감한, 취사가능',
    img: 'https://images.app.goo.gl/Bu6pWYhXspqrAWCv6',
  },
  {
    id: 20,
    businessName: '제주플래티늄카라반',
    phoneNumber: '064-805-9999',
    address: '제주특별자치도 제주시 애월읍 하귀미수포길 5-8',
    latitude: 33.48344137,
    longitude: 126.4013992,
    glampingCount: null,
    caravanCount: null,
    campingDeckCount: null,
    outdoorCampingCount: null,
    hasToilet: null,
    hasShower: null,
    hasWashbasin: null,
    parkingCapacity: null,
    tags: '바다, 별, 카라반, 조용한, 로맨틱한, 아늑한, 평화로운, 바베큐, 청결에 민감한',
    img: 'https://images.app.goo.gl/hrKYhYZQugTmYfEf8',
  },
  {
    id: 21,
    businessName: '베스트힐펜션&글램핑',
    phoneNumber: '070-4400-3300',
    address: '제주특별자치도 제주시 조천읍 남조로 2109-36',
    latitude: 33.4538433,
    longitude: 126.657768,
    glampingCount: '10',
    caravanCount: '0',
    campingDeckCount: '0',
    outdoorCampingCount: '0',
    hasToilet: '0',
    hasShower: null,
    hasWashbasin: null,
    parkingCapacity: 30,
    tags: '신나는, 친근한, 개방적인, 도전적인, 취사가능, 글램핑',
    img: 'https://images.app.goo.gl/UixQ4aXyZT5v99T49',
  },
  {
    id: 22,
    businessName: '제주교래자연휴양림야영장',
    phoneNumber: '064-710-7475',
    address: '제주특별자치도 제주시 조천읍 남조로 2023 교래자연휴양림',
    latitude: 33.44159863,
    longitude: 126.6648469,
    glampingCount: '0',
    caravanCount: '0',
    campingDeckCount: '0',
    outdoorCampingCount: '0',
    hasToilet: '40',
    hasShower: null,
    hasWashbasin: null,
    parkingCapacity: 134,
    tags: '조용한, 아늑한, 평화로운, 시원한, 들판, 별, 청결에 민감한',
    img: 'https://images.app.goo.gl/2JTEiZFL1pwiCPHg7',
  },
  {
    id: 23,
    businessName: '귤빛캠핑장',
    phoneNumber: '064-782-0110',
    address: '제주특별자치도 제주시 조천읍 함와로 428',
    latitude: 33.5049705,
    longitude: 126.6743345,
    glampingCount: null,
    caravanCount: null,
    campingDeckCount: null,
    outdoorCampingCount: null,
    hasToilet: 'Y',
    hasShower: 'Y',
    hasWashbasin: 'Y',
    parkingCapacity: null,
    tags: '신나는, 개방적인, 시원한, 도전적인, 카라반, 물놀이 시설, 청결에 민감한, 반려동물 친화적인, 취사가능',
    img: 'https://images.app.goo.gl/CtbqYmV6te5xsmAYA',
  },
  {
    id: 24,
    businessName: '골체오름캠핑',
    phoneNumber: null,
    address: '제주특별자치도 제주시 조천읍 번영로 1648-41',
    latitude: 33.45142976,
    longitude: 126.7053226,
    glampingCount: null,
    caravanCount: null,
    campingDeckCount: null,
    outdoorCampingCount: null,
    hasToilet: null,
    hasShower: null,
    hasWashbasin: 'Y',
    parkingCapacity: null,
    tags: '개방적인, 평화로운, 시원한, 청결에 민감한, 바베큐, 취사가능, 들판, 별',
    img: 'https://images.app.goo.gl/Zvbu9SBjmLm4J6Xm9',
  },
  {
    id: 25,
    businessName: '무거카라반',
    phoneNumber: null,
    address: '제주특별자치도 제주시 조천읍 조함해안로 352',
    latitude: 33.54909682,
    longitude: 126.6551938,
    glampingCount: null,
    caravanCount: null,
    campingDeckCount: null,
    outdoorCampingCount: null,
    hasToilet: null,
    hasShower: null,
    hasWashbasin: null,
    parkingCapacity: null,
    tags: '조용한, 아늑한, 평화로운, 시원한, 취사가능, 카라반, 들판, 별',
    img: 'https://images.app.goo.gl/jQitkm6sxH2wrumR6',
  },
  {
    id: 26,
    businessName: '돌하르방캠핑장',
    phoneNumber: '064-773-0102',
    address: '제주특별자치도 제주시 한경면 낙수로 271-40',
    latitude: 33.32386917,
    longitude: 126.2390243,
    glampingCount: '23',
    caravanCount: '20',
    campingDeckCount: null,
    outdoorCampingCount: null,
    hasToilet: null,
    hasShower: 'Y',
    hasWashbasin: 'Y',
    parkingCapacity: 4,
    tags: '조용한, 아늑한, 로맨틱한, 친근한, 반려동물 친화적인, 취사가능, 물놀이 시설, 들판, 별',
    img: 'https://images.app.goo.gl/UEGX8gTMxCTC5Fq3A',
  },
  {
    id: 27,
    businessName: '비체올린캠핑장',
    phoneNumber: '0507-1327-2800',
    address: '제주특별자치도 제주시 한경면 판조로 253-6',
    latitude: 33.34946014,
    longitude: 126.2185652,
    glampingCount: null,
    caravanCount: null,
    campingDeckCount: null,
    outdoorCampingCount: null,
    hasToilet: 'Y',
    hasShower: null,
    hasWashbasin: null,
    parkingCapacity: null,
    tags: '신나는, 도전적인, 개방적인, 시원한, 들판',
    img: 'https://images.app.goo.gl/ZdFXtFsapFsGuG6B6',
  },
  {
    id: 28,
    businessName: '금능해수욕장 야영장',
    phoneNumber: '064-728-3983',
    address: null,
    latitude: 33.39107647,
    longitude: 126.2361338,
    glampingCount: null,
    caravanCount: null,
    campingDeckCount: null,
    outdoorCampingCount: null,
    hasToilet: 'Y',
    hasShower: 'Y',
    hasWashbasin: 'Y',
    parkingCapacity: 94,
    tags: '신나는, 도전적인, 개방적인, 평화로운, 물놀이 시설, 들판',
    img: 'https://images.app.goo.gl/6HnAs9HRAJvFCJni6',
  },
];

export default allData;
